### ISSUE TITLE
Get organization networks

### ISSUE THREAD

**Issue by obrigg** [jbogarin/meraki-ansible-test#21]
cisco.meraki.networks_info

Based on the code, this module should either provide the list of networks per organization (if an organization Id is provided), or the details of one networks (if a network ID is provided). I tried both:

Get all networks:
```
---

- hosts: meraki_servers
  vars:
    organization_id: 828099381482762270
  gather_facts: false
  tasks:
    - name: Get all Organization networks
      cisco.meraki.networks_info:
        meraki_suppress_logging: true
        organizationId: "{{ organization_id }}"
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
```
failed with:
```
(ansible) Oren.Brigg@OBRIGG-M-9VFC playbooks % ansible-playbook -i hosts organization_info.yml -vvv
ansible-playbook [core 2.15.1]
  config file = None
  configured module search path = ['/Users/Oren.Brigg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/Oren.Brigg/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/bin/ansible-playbook
  python version = 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] (/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/bin/python)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/hosts as it did not pass its verify_file() method
script declined parsing /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/hosts as it did not pass its verify_file() method
auto declined parsing /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/hosts as it did not pass its verify_file() method
Parsed /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: organization_info.yml **********************************************************************************************************************************************************************************
1 plays in organization_info.yml

PLAY [meraki_servers] ********************************************************************************************************************************************************************************************

TASK [Get all Organization networks] *****************************************************************************************************************************************************************************
task path: /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/organization_info.yml:18
The full traceback is:
Traceback (most recent call last):
  File "/Users/Oren.Brigg/.ansible/collections/ansible_collections/cisco/meraki/plugins/plugin_utils/meraki.py", line 248, in exec_meraki
    family = getattr(self.api, family)
AttributeError: 'DashboardAPI' object has no attribute 'organizationsnetworks'
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible.plugins.callback.default.CallbackModule object at 0x10440d8a0>): Object of type AttributeError is not JSON serializable
Callback Exception:
  File "/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible/executor/task_queue_manager.py", line 468, in send_callback
    method(*new_args, **kwargs)
   File "/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible/plugins/callback/default.py", line 67, in v2_runner_on_failed
    msg = "fatal: [%s]: FAILED! => %s" % (host_label, self._dump_results(result._result))
   File "/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible/plugins/callback/__init__.py", line 258, in _dump_results
    return json.dumps(OrderedDict(sorted(abridged_result.items(), key=to_text)),
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
   File "/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible/module_utils/common/json.py", line 75, in default
    value = super(AnsibleJSONEncoder, self).default(o)
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

PLAY RECAP *******************************************************************************************************************************************************************************************************
meraki_server              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
Get one network:
```
---

- hosts: meraki_servers
  vars:
    network_id: "L_828099381482771185" # Branch-1234
  gather_facts: false
  tasks:

    - name: Get all Organization networks
      cisco.meraki.networks_info:
        meraki_suppress_logging: true
        networkId: "{{ network_id }}"
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
```
failed with:
```
(ansible) Oren.Brigg@OBRIGG-M-9VFC playbooks % ansible-playbook -i hosts organization_info.yml -vvv
ansible-playbook [core 2.15.1]
  config file = None
  configured module search path = ['/Users/Oren.Brigg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/Oren.Brigg/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/bin/ansible-playbook
  python version = 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] (/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/bin/python)
  jinja version = 3.1.2
  libyaml = True
No config file found; using defaults
host_list declined parsing /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/hosts as it did not pass its verify_file() method
script declined parsing /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/hosts as it did not pass its verify_file() method
auto declined parsing /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/hosts as it did not pass its verify_file() method
Parsed /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: organization_info.yml **********************************************************************************************************************************************************************************
1 plays in organization_info.yml

PLAY [meraki_servers] ********************************************************************************************************************************************************************************************

TASK [Get all Organization networks] *****************************************************************************************************************************************************************************
task path: /Users/Oren.Brigg/Python/ansible/meraki-ansible-test-oren/playbooks/organization_info.yml:18
The full traceback is:
Traceback (most recent call last):
  File "/Users/Oren.Brigg/.ansible/collections/ansible_collections/cisco/meraki/plugins/plugin_utils/meraki.py", line 248, in exec_meraki
    family = getattr(self.api, family)
AttributeError: 'DashboardAPI' object has no attribute 'organizationsnetworks'
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin (<ansible.plugins.callback.default.CallbackModule object at 0x104b7d8a0>): Object of type AttributeError is not JSON serializable
Callback Exception:
  File "/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible/executor/task_queue_manager.py", line 468, in send_callback
    method(*new_args, **kwargs)
   File "/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible/plugins/callback/default.py", line 67, in v2_runner_on_failed
    msg = "fatal: [%s]: FAILED! => %s" % (host_label, self._dump_results(result._result))
   File "/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible/plugins/callback/__init__.py", line 258, in _dump_results
    return json.dumps(OrderedDict(sorted(abridged_result.items(), key=to_text)),
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
   File "/Users/Oren.Brigg/.local/share/virtualenvs/ansible-tkGtej5D/lib/python3.10/site-packages/ansible/module_utils/common/json.py", line 75, in default
    value = super(AnsibleJSONEncoder, self).default(o)
   File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

PLAY RECAP *******************************************************************************************************************************************************************************************************
meraki_server              : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by obrigg** [comment]
I am not sure why, but changing `family="organizations"` to `family="organizationsnetworks" ` [here](https://github.com/jbogarin/meraki-ansible-test/commit/520fa6ee88a869bc198195c736a9aec72a08e992#diff-e2368af6058d7fa3e7e3d9c6ff6922d0286a6139e4e96bd48a62003d1e4f229b) caused this regression. reverting it back allowed network_info to work again.
